# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 07:55
from __future__ import unicode_literals

import agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=61, unique=True)),
                ('hostname', models.CharField(default='', max_length=128)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('mac', models.CharField(default='', max_length=32)),
                ('paltform', models.CharField(default='', max_length=128)),
                ('arch', models.CharField(default='', max_length=16)),
                ('cpu', models.IntegerField(default=0)),
                ('mem', models.BigIntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('time', models.FloatField(default=0)),
                ('user', models.CharField(default='', max_length=64)),
                ('application', models.CharField(default='', max_length=64)),
                ('addr', models.CharField(default='', max_length=256)),
                ('remark', models.TextField(default='')),
                ('heartbeat_time', models.DateTimeField(auto_now_add=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
            },
            bases=(agent.models.ASDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.FloatField(default=0)),
                ('mem', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'resources',
            },
            bases=(agent.models.ASDictMixin, models.Model),
        ),
    ]
