# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(default='cmdb123', max_length=512)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('registe_time', models.DateTimeField(auto_now_add=True)),
                ('login_time', models.DateTimeField(null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
